### ISSUE TITLE
move the translucent panel to the up/down side OR change Y axis price location

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/frequi#1016]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/1921878/202489981-e848b3bf-f800-45c7-b659-7bcb9d9b42a0.png)

When hovering the mouse on candles of the right side of the screen, the translucent panel automatically move to the left -- this is good.

However, it covers the Y axis and the price of the current mouse position.

**Describe the solution you'd like**
A clear view of the price of where the mouse is currently located.

**Describe alternatives you've considered**
Would it be possible to also position the panel based on the up/down position of the mouse/candle?
Or also change the Y label of the chart?

**Comment by xmatthias** [comment]
the panel itself is moved all the way to the side so it's not blocking the view to the chart.
we could obviously move it to the right by "labels width" - but i'm not sure that's a better solution.

> Would it be possible to also position the panel based on the up/down position of the mouse/candle?

i'm not certain what you mean with this. i think having the panel "at the mouse height" would actually be worse.

**Comment by xmatthias** [comment]
I'd not know how to improve behavior here without causing other problems in either obstructing view of the chart, or moving it statically to the right (which would obstruct view on the chart even more).

If you have a proposal on how / where this can be moved feel free to make a suggestion, otherwise i'll be closing this issue in a week.

Please keep in mind however that your configuration is quite odd / empty - and it has to work for configurations as the following (which effectively means - tying it to the bottom when the mouse is at the top is not going to work):
![image](https://user-images.githubusercontent.com/5024695/202635445-dfed9f00-72f0-4fd4-9976-2c3968f12230.png)

**Comment by xarthurx** [comment]
To me, since the right part has no axis info (like in Binance, they use the y-axis on the right for volume info, img below), we can just duplicate the y-axis price on the right.
![image](https://user-images.githubusercontent.com/1921878/202673149-4a5e4070-c25c-4ae3-9d40-d3c701919cc7.png)


But I will respect your decision. For me, it is just a bit inconvenient in some cases.

**Comment by xmatthias** [comment]
The binance chart has the scale only on the right by default - (and the volume is below, not merged into the same plot).

Now moving the scale to the right would be an option - but would just move the problem from left to right.

**Comment by xarthurx** [comment]
![image](https://user-images.githubusercontent.com/1921878/202743719-be579b25-c6a5-460f-b1b6-34bcafc19e82.png)

Another approach is just add a bit padding, leaving the text not covered by the frame.
If you don't like either, you can close the issue.

Thank you for your time.

**Comment by xmatthias** [comment]
closed by db42bbc
