### ISSUE TITLE
show volume in stake-currency instead of just coin-volume

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/frequi#1225]
**Is your feature request related to a problem? Please describe.**
I find it quite confusing some times when looking at either high-valued or low-valued coins in determining "is it having much volume or low volume now" having to manually do calculus everytime this question pops up.

**Describe the solution you'd like**
An additional line along the lines of "volume in USDT / BUSD / BTC" (whatever it currently is, a simple multiplication) would help imo.

**Additional context**
![grafik](https://user-images.githubusercontent.com/41228167/235374098-9a482ad6-4dbc-49fc-a009-674bff5791c8.png)

This really is no urgent thing, just a suggestion. :)

**Comment by xmatthias** [comment]
are we talking about the graphic - or about the tooltip? (The tooltip is autogenerated based on the added series ...).

Do exchanges show both the base and quote volume? that's new to me - usually it's one of the two - and you have to guess / experiment to find out which one is ACTUALLY shown :laughing:

**Comment by hippocritical** [comment]
sad, okay thx

**Comment by stash86** [comment]
Just to add example to mathias' answer, Binance only give you volume in coin-volume, FTX (before the doom) gave you the volume in USD. Not sure how kucoin and others do it.

Last time I checked (because I want to do in-strat volume filter), FT do have a code to detect which volume type is given and convert it appropriately to be used for VolumePairlist. That code probably can be ported to frequi?

**Comment by stash86** [comment]
https://github.com/ccxt/ccxt/issues/10767

**Comment by xmatthias** [comment]
@hippocritical i didn't say no though - i was just asking a basic question (do exchanges show this?).

If they do, we maybe can use it to figure out which rate is used to convert the volume (open, close, average between the two?).
