### ISSUE TITLE
Add an indication when the bot is paused

### ISSUE THREAD

**Issue by macsim26** [freqtrade/frequi#1552]
**Is your feature request related to a problem? No 

**Describe the solution you'd like**
A clear indication that the bot will not enter new trades but still handle open trades

**Additional context**
Hello i have paused my live bot to not enter new trades but i don't see any indication that this is the case nor in FreqUI nor in the logs... Thanks

**Comment by xmatthias** [comment]
Let's start off with the question of "how" you paused the bot (there's 2 ways).

You either issue a "stop" command  (the stop button in the UI) - or did you actually pause the bot? (which will simply set max_open_trades to 0).

In the latter case - the bot is not "actually" paused (only new entries are paused).
It'll still do regular bot handling - as well as allow force-entries and similar.

I'd not know how to show this second part "clearly".
The visual indication is there - but you need to know where to look for it - as it's as simple as a "0" showing as part of the "max_open_trades" setting.

![image](https://github.com/freqtrade/frequi/assets/5024695/4402bfa2-02a0-41e4-8471-0eb6ecb72340)



If you have any ideas on how this should be better displayed - happy to hear and most likely implement - otherwise it'll get "shelved" along with the other issues until someone with a spark of "how to" comes along.

**Comment by macsim26** [comment]
You're right, it works perfectly once you know where to look...
What surprised me was that there was no message in the logs indicating that it had been taken into account.
It would be nice if, in addition to the 0xunlimited indication in the general tab, there were a confirmation message in the log.
In any case, thanks to your clear explanations, I'm sure that my strategy is paused...
