### ISSUE TITLE
[FR] Add price change and % change to candles in UI chart

### ISSUE THREAD

**Issue by chepo92** [freqtrade/frequi#1594]
**Is your feature request related to a problem? Please describe.**
Idk if there exist the option, but would be nice to have the price change and % of change for each candle the FreqTrade UI, 

**Describe the solution you'd like**
Add delta and % change to candle information in the FreqTrade UI 

**Describe alternatives you've considered**
maybe I need to create and populate them as indicator ?, but I don't know if it will add them in candle information section 

**Additional context**
FreqTrade UI:

![imagen](https://github.com/freqtrade/frequi/assets/26207806/635676ae-9470-4325-853d-6ad04d3a6516)

Eg. (coinex shows +0.000891 (+0.67%) ) 

![imagen](https://github.com/freqtrade/frequi/assets/26207806/258d86ab-01a7-433c-ac70-243292969c75)

**Comment by xmatthias** [comment]
define "price change of each candle" ? 
is it low -> high? open -> close? something else? 

it's not defined, really, and i've seen different instances across exchanges over the years.

the easiest is for sure to simply add it as an indicator, and then plot it somewhere - so it'll be shown in the "tooltip" when you mouseover a candle.
it'll be shown in the section you add it to - which most likely will be one of the subplots, as otherwise the scaling will be comletely off, forcing you to zoom in a lot.

**Comment by xmatthias** [comment]
well just use the name for that? 
like - name it "change_%"? pandas will allow that - and so should everything after that.

**Comment by xmatthias** [comment]
You can now use the shift button to interactively measure distances (similar to tradingview charts).

![image](https://github.com/freqtrade/frequi/assets/5024695/f8124c95-16f0-4e02-9a8f-9236413f3a33)

either that - or by adding the % to the dataframe to display it on-chart should do what you require.
