### ISSUE TITLE
in Backtesting / Load results: adding a column "Result" displaying backtest % profit

### ISSUE THREAD

**Issue by eltech35** [freqtrade/frequi#1757]
In the backtest / load results window, adding a column "Result" displaying backtest % profit would definetly be a plus.

The "killer feature" would then to have column headers clickable to sort the tab by Strategy / Result / Timeframe / Backtest time...

This way, comparing backtest results for same strategy would be.... just a click !

**Comment by xmatthias** [comment]
Backtest load-results window is based on quickly loading the metadata files.

I do understand that having additional information here would be beneficial - but loading this is already pretty slow if you have quite a few results aleady (it needs to potentially load 1000nds of metadata files - so every byte counts) - so that's currently not planned.

sorting _may_ be something that can be added in the future (sorting is currently broken in bootstrap-vue-next) - but profit% will not be added.
filtering should be pretty straightforward to add.

**Comment by eltech35** [comment]
I get your point. Thanks for such rapid answer.
