### ISSUE TITLE
Mock/fake api calls during development and test

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#18]
Hi,

We should develop on freqtrade ui with no connection to backed needed.

Maybe use a tool like https://github.com/typicode/json-server.

I don't have benchmark the different tooling we could use nor if freqtrade api use some openApi conventions that can help when using this kind of tool.

Have a nice day.

**Comment by xmatthias** [comment]
Freqtrade cannot use openAPI specification since that does not allow calling methods in classes.
 
So in the end, you'd end up rebuilding the whole freqtrade API again via openAPI (which however can't be used by freqtrade) - which is currently heavily changing as i'm adapting and improving some parts to be used with the UI.

I've tried this when we added the API server to freqtrade in multiple ways - but it does not seem possible.

Without the class though, you won't have access to freqtrade internals - so it can only query the database, but execute no action.


A simple workaround is to start a dry-run bot with a mock database (or a strategy that buys every minute, sells every other minute).
