### ISSUE TITLE
Is frequi consume an api designed to be used by telegram ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#19]
Hi,

Most of the freqtrade api seems to have be design to fit the telegram UI contrains.
When i see frequi>trade got the feeling to be a copy paste of telegram bot results but a website is not a telegram bot in term of UX/UI ?

Maybe i am wrong but it is the feeling that i have (it serve data aggregated to fit telegram format and so not very easy to produce dashboard?)

Have a nice day.

**Comment by xmatthias** [comment]
well if you consider the history of the RPC Components in freqtrade, it was originally developed for telegram, and only later adapted to provide similar answers as REST (that's why the REST APi is currently changing a lot ...).

---

Now i'm not sure what exactly it is you disagree with specifically - balance / open (and closed) trade view and /whitelist seem fine to me to do "daily operations".

Also, trade endpoints (open / closed trades) do provide the full database object (with small deviations for open trades) - so everything we want should be possible based on this data.

However, what i'd like to avoid is to do too much logic in the UI - but have most calculations done in the backend, so other RPC methods (speak telegram) can benefit from it eventually.

However, new endpoints (also rest-only endpoints without a telegram counterpart) can be added to freqtrade as necessary - but so far i've not encountered anything that's "completely missing" - most parts  just miss some information, or provide it in a biased format (timestamps formatted for human eyes...).

One thing that might be worth to point out here is that vuex contains more information than what is currently shown - you can inspect that using the vue extension in chrome (for example).

**Comment by xmatthias** [comment]
As explained above - the API started as a copy of the telegram telegram, so it was not made for a real application.
Since there was no official consumption layer for the API other than the standalone script, it was functional but design was partially lacking.

We're now slowly moving it towards a better API design, with aligned fieldnames to make it easier to be consumed by frequi as issues come up, so i'll close this as i agree in principle - but it's up to us to improve the API layer over time :)
