### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mistycaseyward12** [freqtrade/frequi#2048]
https://github.com/carpentries/instructor-training/commit/2806f4845edafd05bb014bfe88812adaf367c22b

**Comment by xmatthias** [comment]
I'll assume you've created this issue as a mistake.

Please make sure to not continue creating pointless issues, otherwise we'll have to assume you're a bot / spam account and will have to block you from interacting with this organization.

Related: https://github.com/freqtrade/frequi/issues/371#issuecomment-2326388655
