### ISSUE TITLE
Adding onclick() handling to CandleChart (question/support)

### ISSUE THREAD

**Issue by d123456temp** [freqtrade/frequi#2061]
Hi @xmatthias I'm stuck and would be very grateful if you could help me going - I'm a backend developer so maybe I'm missing obvious things...

I wanted to add some action when I click on the candle chart. This should be trivial according to this: https://echarts.apache.org/handbook/en/concepts/event/#

Yet, when I add something like this at the end of  CandleChart.vue:updateChart

```
  candleChart.value?.on('click', function(params) {
    // Print name in console
    console.log("click!: " + params.name);
  });
```

I get: Uncaught (in promise) TypeError: candleChart.value.on is not a function. I can see that you operate on candleChart.value? all over this code, so why registering onclick doesn't work? Is there any way to achieve what I want?

**Comment by xmatthias** [comment]
The problem is pretty likely an execution sequence problem / misunderstanding.

if you place this at the root of the script setup - it'll not be available yet.
SO while we're using it throughout the script - it's always within a function or whatever. (think about it in python - you can't do cyclic imports at the top of the file - within a function, you can usually import whatever you like, even if it's technically a cyclic import).

Placing it someplace within an `onMounted()` should probably work - though to be quite honest - this type of support is not something we're providing here - this is better suited in a vue dedicated forum - as while you've encountered it with freqUI - it's really a "need to understand vue basics first" problem 😆

**Comment by d123456temp** [comment]
@xmatthias  thank you, I understand, sorry about that.
Adding this to onMounted.onMonted() has the same reason. I asked this question, because in the same place I added my code (CandleChart.vue:updateChart), just one line above this code of yours work:

candleChart.value?.setOption(chartOptions.value, {
    replaceMerge: ['series', 'grid', 'yAxis', 'xAxis', 'legend'],
    notMerge: initial,
  });

so I guess the "on" hook simply does not work in vue.

**Comment by xmatthias** [comment]
well according to editor completions - candleChart.value has the handlers attached directly - so while ".on" will not work - all ".onClick" would directly work.
