### ISSUE TITLE
add feature min, max, daily guidlines

### ISSUE THREAD

**Issue by denisdemaisbr** [freqtrade/frequi#2093]
**Describe the solution you'd like**
Add optionally a minimal, maximum (1h/24h) e daily close line guides (dashed style)

**Additional context**
![image](https://github.com/user-attachments/assets/3501eabb-8d38-477c-8e6f-14e9d01a8be2)

**Comment by xmatthias** [comment]
If you need this - you can calculate this pretty easily in your dataframe (`dataframe.rolling(24).max()` for 1h candles) - and have this as additional column you can place as indicator.
This has the benefit that the actual "how" is up to you (on tradingview, it's dynamic for whatever you aim to display).

I do however not think that it's beneficial to force random information onto people "just because".

On tradingview, this is not the default view - and it has no specified time unit - but it's showing whatever is visible on screen - which is pretty useless if i'm honest - as it's simply showing the top and bottom of the page.

While you can activate it on tradingview - i don't really see a benefit in this.
While technically it would be pretty simple to add - it's a pointless (it's not providing actually useful information - your bot will NOT be aware of this line), distracting line for no good reason.
