### ISSUE TITLE
New data plotting mechanism

### ISSUE THREAD

**Issue by snussik** [freqtrade/frequi#2102]
## Describe your environment

  * Operating system: Windows 11 Home Single Language 22H2 22621.3447
  * Python Version: Python 3.12.2
  * CCXT version: CCXT 4.2.87
  * Freqtrade Version: freqtrade 2024.4-dev-e6da491ca

## Describe the enhancement

Currently, these capabilities are limited. Displaying a large number of elements in real-time requires significant computational resources, as the data is sourced from the main dataframe.

<img width="1701" alt="Screenshot 2024-10-02 at 21 09 24" src="https://github.com/user-attachments/assets/88c65c86-31dc-4f17-baf3-b9e9628b897d">

After reviewing the issue I raised earlier: https://github.com/freqtrade/freqtrade/issues/10197, I concluded that a method similar to the one used in this project could be more suitable: https://github.com/louisnw01/lightweight-charts-python.

### Main Idea: 
Is to have a global `Chart` object into which various primitives can be added: `lines`, `boxes`, `points`.

**Comment by xmatthias** [comment]
I've moved this to the freqUI repository - as plotting through `plot-dataframe` is considered deprecated.
While we don't plan on removing it - there's also no plans on improving or replacing it. 
It's a static form of plotting - which clearly doesn't scale (as you correctly mention).

FreqUI offers improved plotting capabilities with support for millions of candles (yes, tested).
so from a freqUI point of view - i can't really follow what you're saying, so my assumption is that you're using `plot-dataframe` - not new approaches.

FreqUI plots fine with tons of candles - only for rather long (5m 1y) plots, you can have a slight delay while zooming in - which is however still not really a problem, as you'll not look at 1y 5m candles all day long anyway - but at a zoomed in version.

For backtesting - you'll have to start freqtrade in [`freqtrade webserver` mode](https://www.freqtrade.io/en/stable/utils/#webserver-mode) to get access to the improved plots.

---

> as the data is sourced from the main dataframe.

This is an explicit decision to avoid disconnects between what the bot trades on vs. what you see on the chart (so independent of the charting technology used - this wouldn't change).

Already within python you can see that different libraries often calculate different indicators with (often significant) difference.
If you switch language - that won't get better. 

As a result, you'd not have the "high computation" in the strategy - but in the frontend - but you'd see "these 2 lines crossed - but caused no signals" - while in the python calculations - they didn't (so they couldn't create a signal).

**Comment by snussik** [comment]
@xmatthias 

The key point is that inidicators must be the separate columns in dataframe with scalar values inside.
But on each new bar it can be _different number_ of active "indicators" of the _same type_ and the can intersect

So i'll have to make smth like this:

```python
for i in range(0, ind_limit):
	dataframe[f"inidcator_X_{i}"] = np.nan
```

and them in plot_config:

```python
for i in range(0, ind_limit):
	...
	plot_config['main_plot'].update({
		f"inidcator_X_{i}": ....,
	})
```

The problem is that it's impossible make smth like this, now:

```python
def calc_ind_X(x) -> np.ndarray[ind_X]):  # <- dummy type annotation for illustration
   ...
   return indicators_X_array

dataframe["inidcator_X"] = dataframe.apply(calc_ind_X)

def plot_config(self):
    ...
    plot_config['main_plot'].update({
		f"inidcator_X": ....,
                "type":  CHART_ELEM.box
                "extract_mthd": lambda x: i for i in x # <- or some other way to unpack array

	})

**Comment by xmatthias** [comment]
If it's an indicator (something the bot/strategy bases a decision on) - then it must be in the dataframe. 
Otherwise it's unknown to the bot / strategy. While it may look good - it's actually not relevant - so you may see "this would be a great entry" - but the bot will not know about it.
i don't really see how a different library would change this - as the sourcing principles (data is sourced from the dataframe) would not change.


---


What's the exact usecase you're trying to cover? 
The above code doesn't "really" make sense to me - but probably because the code ismostly anonymized.

From the screenshot it looks like rectangles that are drawn manually - but i don't really see why you'd need these in freqUI? 
If they're not drawn manually - then it's indicators - so they're in a chart already, no?

**Comment by snussik** [comment]
@xmatthias on the pic. above - are computed indicators. But in order to illustrate what I'm trying to do, here is the drawn manually example:

![Screenshot 2024-10-03 152434](https://github.com/user-attachments/assets/5bc7bf79-9938-4d65-b8b2-3896418ad80d)

For ex.: I'd like to plot all not mitigated highs above the current candle (in yellow rectangle) and use this information for my target levels.

It can de done without plotting definitely, but it'll be hard to debug strategy visually.

So, I'd like to see these levels on the chart.

In order to plot them now, its needed to create separate columns in main dataframe. But the number of lines can be any int number from 0 to int16.  And its only one type of indicator. So the number of columns for all such indicators can be huge.

Much easier it could be If i could store an array of start indices of non mitigated levels in a separate "indicator" column in main or dedicated dataframe  and extract these values for plotting with use of some middleware func. 

Thats why I proposed to use dedicated singleton Chart object (and maybe separate plotting dataframe) that can unpack values as needed and add them to plot.

**Comment by xmatthias** [comment]
Well adding _anything_ to `plot_config()` (other than actual configuration) doesn't make sense - that's designed to be read once on demand (on user click) - and considering plot configs can be changed in freqUI (where it's more comfortable to actually change as you got an UI) - i don't see that as transport mechanism.

I assume you're using the "not mitigated highs" (how do you define if it's mitigated??) in the strategy to determine some signals - how are you generating (and storing) these currently?

Can you share a (working, minimal) strategy for me to play around with (essentially one that generates some trading signals off of this - doesn't need to be profitable . . . ) - where the structure actually resamples what you're using currently. 

Ignore (assumed) plotting assumptions / necessities.


For clarity - I'll be looking for the following things in that strategy:

* how are you generating these signals
* how are you storing and using these (so what's the format you're using to have this in a "comfortable" way

ideally - it's complete "enough" so i can just dump it, run it - and see the structure that's being generated - without being overly complicated 1000nds of lines long.

**Comment by snussik** [comment]
@xmatthias  I'll do this. But I need some time to extract working parts of code  as my indicators work as a part of main module and rely on other submodules.

**Comment by snussik** [comment]
@xmatthias I've made strategy example based on the levels of not broken highs and lows. Here is the link: https://gist.github.com/snussik/565e0ec500cb47535c3ce4249e12d902

I'd like to see something like this on the chart during strategy execution:

fig. 1
<img width="581" alt="Screenshot 2024-10-05 at 13 20 09" src="https://github.com/user-attachments/assets/ef1fea15-33f7-4519-9325-034dd124bfce">

fig. 2
<img width="840" alt="Screenshot 2024-10-05 at 13 34 42" src="https://github.com/user-attachments/assets/c18fa6ce-35ac-466f-a548-15e5cd7fcedd">

**Comment by xmatthias** [comment]
Well i'm not sure what conditions have to be met for this to work - but it generated NaN columns throughout the whole dataframe.

i've even added the following snippet at the end of `populate_indicators_1h` - but it's NaN all the time (this is to ensure it's not a serialization problem).

``` python
        dataframe.loc[:, 'hasData'] = 0
        dataframe.loc[
            (e.notna() | t.notna() | s.notna())
            , 'hasData'] = 1
```

Either, it needs specific conditions to be met (which honestly, i lack the time and will to reverse-engineer to try to understand your requirement) - or it's trimmed down to a point it no longer works.

At any rate - i didn't get any output - so with nan in all rows - there's nothing to plot.

Please revise your example (or let me know the conditions that have to be met) so i can just start a bot and look at the output you'd expect.

**Comment by snussik** [comment]
@xmatthias  I've  made some changes so script can be just pasted and executed with debug printing of the main data: https://gist.github.com/snussik/a45e8194dcf0d6996a7aa5ec07f3bde9

Please use the commented command for simplicity.

In fact it doesn't really matter about  (e)ntry , t(akeprofit) and s(toploss) points. They are just for position defining. Main logic is in the `get_sell_signals` - function that uses indicators (levels) data.

The main idea (related) to the issue is that these points are calculated on the basis of levels and their behaviour (change of state). So its extremely useful to see the levels on the chart in order to understand if the strategy was made in a proper way.

**Comment by xmatthias** [comment]
Quite honestly - it's still not making any sense.

for BTC - it's printing something around the following:
![image](https://github.com/user-attachments/assets/b30b64b0-9bae-4ace-a4fe-487af68011f2)

price is ~65k ... but your values get 32 as "height" - which lacks reference to anything (at least i don't understand what this should refer to).
If we were to plot this - it'd plot candles at 65_000$ pricelevel - and the lines at 32$ - which i don't think is what "high" refers to.

This way, it will not be plottable - as it's not referring to any price level, but to a number i have no idea what it intends to refer to (it's clearly not a price).


Whatever "indicators" defines is beyond me - this would plot exactly one line? 
but this is not how plotting works - or is ever gonna work - as it ignores the "we have one point per candle" approach.


One last try - i'd expect a column per candle containing a list of prices where lines should be plotted.
Obviously if you expect the line to be 3 candles long - this price will be at the same position in this list.

With this - you'll essentially get to add 2 columns.
with that - i could try to make plots show all lines within the list.

If that's not possible for you to provide - then i'll have to close this issue as "won't do".

**Comment by snussik** [comment]
@xmatthias 


> price is ~65k ... but your values get 32 as "height" - which lacks reference to anything (at least i don't understand what this should refer to).

32, 33, 34 and so on are the inidices of the candles, whose "highs" weren't broken up to the current 196 candle.

> as it ignores the "we have one point per candle" approach.

It is not. The idea is that (as you see) on each candle we can have many "unbroken" previous highs. So The line that is made from meets this condition: it starts somewhere (on 32, 33 .... and so on candle) and is active till current.  

> One last try - i'd expect a column per candle containing a list of prices where lines should be plotted for this candle.

That is what you see in the high_ column, But in order to save memory and performance its just indices that are extracted as coordinates from line 95 to line 108 of the script.
I've make the example only for 2 lines for performance. 

> With this - you'll essentially get to add 2 columns.
> with that - i could try to make plots show all lines within the list.

With the current plotting implementation its true. But the problem is than on each candle there can be much more "levels" to plot. And The number of additional columns can be huge.

That is why I proposed to change the current plotting implementation in order to separate "trading" and "plotting" data, So user could decide wthat indicators should be plotted and create some middleware for them & add indicators as some standart primitives (text, line, box, scatter) to some global Chart object that can add them to the plot.


p.s.:

> the code is oddly structured / nested

Please consider, that I'm not a programmer and my skills are on the basic level, obviously :)

**Comment by xmatthias** [comment]
> That is why I proposed to change the current plotting implementation in order to separate "trading" and "plotting" data, So user could decide wthat indicators should be plotted and create some middleware for them & add indicators as some standart primitives (text, line, box, scatter) to some global Chart object that can add them to the plot.

Well please understand that replacing an implementation because it doesn't fit one user's _niche needs_ ain't going to happen.

Standard primitives are designed to be manually drawn, really.
You'll not be able to plot this on binance, either - and irrelevant of the implementation - you WILL encounter performance problems with that - as primitives are NOT as optimized as a line - and technically, there's an (implementation) difference between drawing a line with 100k points - and drawing 50k primitives - as the internal optimizations of libraries work for one - but not for the other.

> the code is oddly structured / nested

That's not what i mean :D 
for example, it's using dataclasses instead of strings for column naming (for example) - which to me (seeing the strategy for the first time), doesn't help and has me jump to "what's that doing again" every time - as i really care about the actual name - not what the dataclass is showing.

> 32, 33, 34 and so on are the inidices of the candles, whose "highs" weren't broken up to the current 196 candle.

Well that's quite error-prone - incides can change depending on when and how you use them.

Example: Backtesting will usually get a slightly longer dataframe (specified timerange + `startup_candle_count`) - with `startup_candle_count` being removed for actual backtesting. 
if you then refer to "index 32" - it'll be a different candle after the initial populate_indicators call, depending HOW you access it (.iloc will change as the overall length changes and has the starting candles removed, .loc will not i think (that's the actual number that's written in the index).
Your mode of accessing (at least in the debug way) of `dataframe['column'][<number>]` is affected by this, too.


---

Currently i see two potential ways for this (not sure which one will work yet, or if it'll be worth the effort).

- either, each candle will get one column per type (highs, lows) - containing a list of points for this type
- or it'll be one column per expected line - with wildcard naming (`highs_1`, `highs_2`) - where you can add indicators to the chart in the form of "highs_*" (or something similar).

from a dataframe perspective, i'd like the first one better - but i'm not sure if that's easily handlable in echarts.
From a "ease of usage" perspective, the 2nd one seems better ... but in reality - once we have one, it'll be pretty simple to reformat to the other (it's not from the current examples).


Now the assumption is that this is a simple, nondisruptive addition.
If it's not and requires bigger changes, then this will be too nich for us to support (the final decision on this will happen later :laughing: )

**Comment by snussik** [comment]
@xmatthias  
> either, each candle will get one column per type (highs, lows) - containing a list of points for this type

if I've understood you right. it's what I need.  As I can see in python wrapper it supports various types of data: https://github.com/yufeiminds/echarts-python/blob/e61349fe8c7e87068dc3a981943666f9c4ef2539/echarts/option.py#L108

**Comment by xmatthias** [comment]
> As I can see in python wrapper 

It's not a python problem - you need it in the dataframe, so it's a "how do you prepare the data problem". 

The requirement to plot a line on a candle chart is clear - and i've outlined it above.

> I've tried that but the proble is that you have to limit possible number of "indicator" columns or you'll face performance issues. And even with the limitations it's slow.

If this is not possible, then this concludes this issue - and my summarization of "it's too niche" was correct.

i'll hence be closing this issue as "not planned."
