### ISSUE TITLE
Provide the official FreqUI docker image on dockerhub

### ISSUE THREAD

**Issue by xzmeng** [freqtrade/frequi#2133]
Can we have freqUI docker image so that we can deploy it standalone ?
When using one single UI to control multiple bots, a standalone deployment seems logically more comfortable to me - I can freely remove any bots without worrying about the bundled UI is gone. And we can update it to the latest development branch anytime.

**Comment by xmatthias** [comment]
You'll have noticed that we do have a Dockerfile in the repository. 
we could publish that to dockerhub / ghcr - 
but I'm not necessarily convinced that's a great idea.

At first, it sounds like a small request - but i think it comes with quite some strings attached (which essentially, we'd need to support at least up to a certain point).


The "proper" way to run freqUI in standalone is through nginx (or essentially every other reverse proxy) - as it's really just a random bunch of html/js files.

If you're doing that however, you'll most likely need quite some configuration (certificates, proxy routes for individual bots so you can actually connect to these easily and through tls, ...).
The alternative is to mess with CORS (Which again, will only work if everything is either https - or the UI is http only (otherwise browsers will block the cross protocol requests, as you can't go from https UI to http endpoints).


most likely, no problem for someone who's ever setup a proxy before - but the intersection of freqtrade users and "users having configured a reverse proxy before" is not as high as we'd like (not if we take the amount of CORS problems as any indicator, anyway).

This essentially means that we'd (try to) support reverse proxy configuration / setups for users - which i don't think is something we should spend our time with.


As long as your bots are on any localhost adress, you can use `https://frequi.netlify.app/` or `https://frequi.vercel.app/` (a hosted version of the main branch) - though it'll not work if your bots are on remote hosts unless you've set them up with https (https -> http problem again).

**Comment by xmatthias** [comment]
Docker image is now available either through docker hub (https://hub.docker.com/r/freqtradeorg/frequi) - or from ghcr (https://github.com/freqtrade/frequi/pkgs/container/frequi).
