### ISSUE TITLE
Add to dockerhub

### ISSUE THREAD

**Issue by devdems** [freqtrade/frequi#225]
Create an image on the docker hub so it will be up to date with the repo.

You can make it as an alpha tag as it is still in that stage.

**Comment by xmatthias** [comment]
we MAY go that route at a later point if the below does not work as i expect (but it does, i already tried it).

The more likely way will however be that we'll integrate it into freqtrade directly, so when you start freqtrade (say `freqtrade trade ...`) - you can access it directly via `http://localhost:8080/ui` (or something similar).

Because of this, the docker image would then become unnecessary.

Hope this makes sense

**Comment by devdems** [comment]
It does. That would be even better.
