### ISSUE TITLE
The y-axis of the graph displays wrong value

### ISSUE THREAD

**Issue by ronangaillard** [freqtrade/frequi#283]
**Describe the bug**
The y-axis cursor sometimes display the wrong value. For instance the cursor displays `454.59` instead of a value more near `1283`
![image](https://user-images.githubusercontent.com/5607736/109792876-455f5d80-7c14-11eb-8a5c-88eb59031937.png)

**To Reproduce**
1. Go to the `/trade` route
2. Move the mouse on the history chart

**Expected behavior**
The y-axis cursor should show the right value

**Screenshots**
![image](https://user-images.githubusercontent.com/5607736/109792876-455f5d80-7c14-11eb-8a5c-88eb59031937.png)
![Mar-03-2021 11-39-27](https://user-images.githubusercontent.com/5607736/109793598-290ff080-7c15-11eb-9fd5-9dbf5299028e.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.1
 - Browser : Bugs tested and spotted in Safari 14.0.3 and Chrome 88.0.4324.192

**Comment by xmatthias** [comment]
I'm not certain it's something we can fix without breaking the layout of the chart / hard-seperating the volume from the chart.

The value you're seeing comes from the Volume (at leaset in my tests) - which is (slightly) merged into the main chart - depending on the overall height of the chart.

**Comment by ronangaillard** [comment]
Oh I understand now.

Maybe it should not be considered as a bug then ?

**Comment by sauces1313** [comment]
Looking at the images and .gif @ronangaillard included, it looks like the price value is displayed behind the volume value (can partially see the last digit).

@xmatthias maybe this could be fixed by having the two values displayed side by side when the cursor is in the respective area? If so, I believe the layout would not need to be changed nor would the volume would need to be separated.

(I would just try to fix it and open a PR, but my coding skills are currently weak (but improving!), so someone else may want to knock it out quicker than I can).

**Comment by xmatthias** [comment]
I don't think that will work - and a fix would need to happen at echarts level. Rendering of these values is not part of freqUI directly.

**Comment by sauces1313** [comment]
Understood. Sorry for the half-cocked suggestion... Today was the first time I've used the UI, which looks fantastic btw. I'll keep looking for ways to help :)
