### ISSUE TITLE
Red and green colours

### ISSUE THREAD

**Issue by jej** [freqtrade/frequi#294]
**Is your feature request related to a problem? Please describe.**
Red color too dramatic in the open trades! Some negative trades are not so dramatic.

**Describe the solution you'd like**
I would like to have an option to display undecided trades in grey, as long as they are within a certain range. Beyond that they could be coloured. For example:
```
<=0.5% : red
>-0.5% && <0.5% : grey
>0.5% : green
```
If I am courageous I will setup the frequi dev env to give my coin :)

**Comment by xmatthias** [comment]
it's not about dramaturgy, but about simple facts.

A candle will also have eihter a green or red color - even if the movement within this candle was almost nothing.

It'll also heavily depend on the usecase / strategy - if you're running a strategy that constantly does 5% wins - sure, 0.5% will be neglectible for you.
If you're however running a strategy that does a lot of small trades (1% or so) - then 0.5% is already halfway to your goal, so i think this is way too subjective to take a decision, therefore basing it on facts (this trade is positive / negative) is the best decision.

**Comment by jej** [comment]
yep I agree it's formally true to have red/green. The idea was just an option, in case...
Thx.

**Comment by Heistergand** [comment]
I support the fact that it's exact two different colors. 

What would be great is the option to choose what two colors to use. Thinking of red/green disabled people, orange/blue is a common option.

**Comment by Heistergand** [comment]
And once again, a developer doesn't care about accessibility. Didn't expect anything else.

**Comment by xmatthias** [comment]
@Heistergand you should **read what the issue is about** before commenting at random. (i could also say  "and once again, a user complaining without even reading what it's about.").

---

This issue is **not** about accessibility / about the colors selected - but about the level after which a trade is determined as red / green.
That's not something that we'll be looking at - as it's clear that a trade that is losing is red / negative color, and a trade that's winning is green / positive color.

What you're talking about is the color selection per se - which is still open and in #1158.


Please keep in mind that this is an open source project. We spend our free time to work on this.
This means that people have the freedom to choose what they'd like to work on next, while still being attacked for not working on what other people think should be priority.

if you care about that topic (choose random colors), i'm more than happy to see a Pull Request from you (it's your choice / free time in that case).
Otherwise - please wait until we've had time to look at #1158. 

Please also take care about your tone - i'll not tolerate verbal abuse of contributors here (myself and other contributors).

**Comment by Heistergand** [comment]
You're right. Sorry for the tone.
