### ISSUE TITLE
Business value of multi-theme ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#49]
Hi,

Not very important but multi-theme :
- Add new lines in code and so should cost maintenance at the end but don't give extra feature. (i' ve been thinking of that because of #47)
- If we need a custom color/design for whatever reason it may not fit all themes.

But of course multi theme is funny and we are geeks :-)

Have a nice day.

**Comment by xmatthias** [comment]
Business value is a bad term here i think ... 

it's all free - there's also no ROI for developing this, really (other than having fun doing so).
i can run the bot perfectly fine from the terminal - so this UI will not make me more profits ....

---

now for multi theme - i would want to have a light / dark theme - as styles in this regard are quite different.

Now creating a theme ourselfs (light / dark) (at the current stage) does not make much sense (it's quite a big time investment - and does make little sense until the functionalities are stable).

The themes bootswatch do provide some variation, so people can pick what they like "for the moment".

The problem with bootswatch themes is that they'll only have 2 or 3 "pairs" - where a light and dark variant fit's together (unfortunately, these are themes that are quite "spacious" - and as trades you'll not want big spaces around stuff - but a lot of information without scrolling around - so they're no good fit).

Now i suspect that in the end, we'll only have 2 themes (one light / one dark).
Ideally, these are (at least to some extend) customized - creating some kind of brand identity for freqtrade (other than a terminal and a screenshot of an (old) version of telegram).

However, since i'm no designer - rest assured that it'll take a long time for this to happen - at least if it should look at least somewhat decent.
