### ISSUE TITLE
timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by botzill** [freqtrade/frequi#517]
**Describe the bug**
When I refresh the UI trades pairs are not loaded with proper data(profit):

<img width="316" alt="Screen Shot 2021-10-05 at 14 24 00" src="https://user-images.githubusercontent.com/4686040/136013757-dd45815f-9305-4213-8b5f-13ea5aba74ca.png">

In chrome I see the following error in console:

<img width="532" alt="Screen Shot 2021-10-05 at 14 22 20" src="https://user-images.githubusercontent.com/4686040/136013887-a6195704-8ea6-4a58-945b-5391ae05c205.png">

Is there a way to change this timeout via envs?

I see it hardcoded here: https://github.com/freqtrade/frequi/blob/d464f12121f8d72b375ef3a8b97b3607ffa4ed5a/src/shared/apiService.ts#L6.

It gives this error on `status` API endpoint. 

Thanks.

**Comment by xmatthias** [comment]
What versions are you using? (for both freqtrade and freqUI)

**Comment by botzill** [comment]
Using latest freqtrade and ui, yes on endpoint `/status/`

**Comment by xmatthias** [comment]
How many trades have you got open trades for? 
What exchange are you using?

**Comment by botzill** [comment]
We have more than 160 open trades and seems it does not manage to load all in 10 seconds, I did increase that, and works ok. We are using finance.

**Comment by botzill** [comment]
I think would be good to have some way to change that via some ENV?

**Comment by xmatthias** [comment]
The UI will be the least of your problems.
With this many trades, one bot-loop will take several seconds (probably minutes).

You'll therefore see a lot of late sells (potentially missed ROI / stoplosses) - simply because the trade that's supposed to be sold has not been checked in time.

I'll therefore consider this as a very edge-case (which probably causes other severe problems) - and therefore as very low priority.

**Comment by botzill** [comment]
I see, we will see check if we can lower the trades number, but I guess having a bigger timeout is not a problem, we can have a default of 20-30 seconds and the UI will work for more use cases.

**Comment by xmatthias** [comment]
Having a higher timeout is problematic if the bot is not reachable (vpn / ssh tunnel down) - as it'll lock up a lot of JS threads.
With this many trades, i'd also suggest to not run auto-update - as that will put even more stress on the backend - which will already be rather slow due to respecting rateLimits.

**Comment by botzill** [comment]
What would be the optimal number of open trades per bot? if we want to have more trades we just need to create another bot?

**Comment by gaugau3000** [comment]
To give feedback :

I make some test with 20 000 trades in database with PostgreSQL, MySQL, sqlite :
-> PostgreSQL succeed to render < 10 s balance and 60 s to render all UI.
-> Mysql and Sqlite failed due to timeout.

The api end-points that bottlenecks/timeouts are:
-> daily?timescale=30
-> balance
-> profit

So PostgreSQL seems a good option with large number of trades.

Matthias i am not sure to understand why a higher timeout is problematic, is the vpn/ssh tunnel is down you will just have the info a bit later ?

Have a nice day.
