### ISSUE TITLE
Easier Selection of Pair

### ISSUE THREAD

**Issue by maumi** [freqtrade/frequi#568]
**Is your feature request related to a problem? Please describe.**
The Pair Selection dropdown sort the Pairs like they are sorted for the trader. That's good if you try to look why exactly this trade was bought. But if you want to look for a specific pair you need to scroll through the whole list. 
I know on a regular pc you can just type in the letters for the trade you are searching for but this won't on an ipad or mobile.

**Describe the solution you'd like**
I would suggest a quick select for the pairs, so pe a textbox where you can type BTC and select the BTC in the dropdown. 
Or make this jump possible per api call like ...:8080/graph?pair=btc
Another alternative would be to add in the settings a bool to sort the pair list (in the dropdown) alphabetically.

**Comment by xmatthias** [comment]
the pairs are (intentionally) sorted in the sequence of the pairlist with small modifications (pairs with open trades on top, locked pairs at the bottom).

Having an additional UI element might work for desktop - but i think it would've need to be hidden on mobile due to space, so i'm not sure that's an approach that would fill your need.

Doing it via route would be a possibility, but not a good one if you ask me.
first of all, it'd have to be the full pair (pair=BTC/USDT) - but the big downside is that it'll cause a page reload (other navigation happens within JS, not as page reload) - so it'll do all "startup calls" against the bot again, which will mean switching this way will be pretty slow.

**Comment by maumi** [comment]
In my Setup Tee Open trades Are Not on top.
Ans idea hey? I use The version implemented in freqtrade. 
This sorting would help me much. 
I'm not sure how easy this could be done but another approach could be a Jump link from the trade overview so to Jump in to the selected pair maybe also als Action like force sell.

**Comment by xmatthias** [comment]
The "trades on top" might only be implemented for the combined pairlist (trade page - where also locks are visualized).

The "graph" panel does not allow Actions - nor should it if you ask me - as we have the trade page for this - which allows for "full" interactivity. Having this all over the place might lead to confusion - and to wasted real-estate if you don't intend to use it.

**Comment by maumi** [comment]
Okay, thanks for your explanation
