### ISSUE TITLE
TradingView chart widgets

### ISSUE THREAD

**Issue by alexpunct** [freqtrade/frequi#574]
**Is your feature request related to a problem? Please describe.**
The existing chart is not very user friendly and some times I have multiple time frames I'd like to see at once which is not possible with the current setup.

**Describe the solution you'd like**
Include one or more Tradingview chart widgets https://www.tradingview.com/widget/advanced-chart/ and be able to create multiple widgets via the strategy or config json object. Something like:

```
tradingViewCharts: [
  {
  "autosize": true,
  "symbol": "NASDAQ:AAPL",
  "interval": "D",
  "timezone": "Etc/UTC",
  "theme": "dark",
  "style": "1",
  "locale": "en",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "withdateranges": true,
  "hide_side_toolbar": false,
  "allow_symbol_change": true,
  "details": true,
  "studies": [
    "BollingerBandsWidth@tv-basicstudies"
  ],
}
]
```

If that's too hard, at least include a link to a custom chart layout. You would specify the chart_id in the configuration and then it would generate a link in the format: `https://www.tradingview.com/chart/${CHART_ID}/?symbol=${SYMBOL}:${TICKER}` which would be included somewhere at the top of the content window in /trade

**Comment by xmatthias** [comment]
The way freqUI implements charts is to ensure you're seeing the indicators how the bot is using them.
Tradingview uses mostly closed-source indicators, which often deviate from the original paper - and therefore also from ta-lib generated indicator lines.

To reduce confusion, this is therefore not something we'll consider.

If you think the charts are not very user friendly, feel free to propose enhancements

using tradingview will not be possible for the following reasons:
* Using the widget you propose uses indicators which are potentially different to the ones freqtrade internally uses, creating conflicting information
* using the tradingview light-charts (a trading library) is not possible due to their licensing.

**Comment by xmatthias** [comment]
I don't think jquery plays well with vue ... (but i didn't try, and jquery is kinda last century ...).

that said - allowing custom javascript (or any user-provided javascript) is a security issue (you could have someone inject code into your environment through some obscure ways) - so no - that'll definitely not be something we will or can support, as it raises the possibility of successful attacks - and freqtrade IS something that needs to be careful on this - as users give it access to their Crypto funds - some small, some bigger - so trust is a must.
