### ISSUE TITLE
Rename bot

### ISSUE THREAD

**Issue by abbaselmas** [freqtrade/frequi#614]
**Is your feature request related to a problem? Please describe.**
There is no problem. I just want to rename already added bots without removing and adding again.

**Additional context**
I am trying mutliple strats and can only see the strats name under trade-->general. However, I want to see the strat name on the bot name. While adding bots i may change the bot name but i keep chaning the strats but not keep removind and adding bots on freqUI

**Comment by xmatthias** [comment]
There is currently no UI for this, that's correct.
there are however 2 ways to do this (one you discovered already)
* remove the bot, and add it again with a new name
* open developer settings (f12 in chrome), navigate to "application" -> local storage - and change the "botName" in the `ftAuthLoginInfo` setting.

It's for sure not ideal (and i'm fully aware of this) - but for now, a "change bot" functionality has not yet been added in a first step.
i'd also want to be able to change the API url, or username/password, should that change for some reason - but didn't find the time to implement that until now (also because it's something "Nice to have" - not something that'll really make anyone any more $ - and as such, is pretty low priority - as it can be worked around with very little effort.

**Comment by abbaselmas** [comment]
> * open developer settings (f12 in chrome), navigate to "application" -> local storage - and change the "botName" in the `ftAuthLoginInfo` setting.

thanks for the second option, at least it is more easy for me.
