### ISSUE TITLE
buy on signal

### ISSUE THREAD

**Issue by anakein** [freqtrade/frequi#792]
We can now force a entry from the UI panel.

if we wanted to use freqtrade ui manually, without automatic buying processes, that only shows the buy signal but it is not executed, it can be programmed in the strategy, Perfect but.

Could it be added that when clicking on the buy signal, a popup appears to make the purchase manually?

thanks

**Comment by xmatthias** [comment]
if you have a buy signal - then freqtrade will also act on it (unless you have reached `max_open_trades`, or are out of balance, ...).

As in each of these cases, you also cannot use forcebuy - your request makes little to no sense.


You can obviously use the regular forceentry method - but we'll not be adding such functionality to the chart - simply because it doesn't belong there.
