### ISSUE TITLE
Graphs under Visualize Summary wrong height

### ISSUE THREAD

**Issue by daniila** [freqtrade/frequi#879]
**Describe the bug**
The graphs under Visualize Summary in webserver mode are illegible because of some kind of height issue or something like that.

**To Reproduce**
1. Go to 'Run Backtest'
2. Finish Backtest
3. Go to 'Visualize Summary'

**Expected behavior**
Profit curve and Trades Log visible and readable

**Screenshots**
https://cdn.discordapp.com/attachments/779658156467814421/1002581200021504040/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (also same on chrome, edge and brave)
 - Version 102.0.1

**Comment by xmatthias** [comment]
One issue might be that the 2nd chart is empty - which is not how it should be - but is fixed now (or rather in the next release).

The issue of the chart was an interesting one - the css class application changed between build and dev version - which is why i've never seen this.
it's however fixed now, and will be included in the next release.
