### ISSUE TITLE
SASS over just CSS ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/frequi#9]
Hi,

SASS is a css pre-processor that give ability to use variables, mixins so help to keep you code dry.
If you would like to change css framework look most of the time they tell you what sass variable overwrite and ensure not to have side effets in the UI.

https://bootstrap-vue.org/docs/reference/theming

Have a nice day.

**Comment by xmatthias** [comment]
is "yes i agree - PR please" a valid answer? 😆 

i mean - we're not using CSS extensively - only in some Vue components - where (to my understanding of vue) you can use a mix of both css and scss (i think SCSS is the new SASS)

So yes to css preprocessor - but i'd use SCSS instead of SASS (even the SASS documentation reccomends SCSS as "more popular" language ) 

> The SCSS syntax uses the file extension .scss. With a few small exceptions, it’s a superset of CSS, which means essentially all valid CSS is valid SCSS as well. Because of its similarity to CSS, it’s the easiest syntax to get used to and the most popular.

[source](https://sass-lang.com/documentation/syntax)

**Comment by gaugau3000** [comment]
In fact sass is the pre-processor and you can use scss and sass language (and i only use scss too) so we are on the same page :-)
